# Generated by Django 3.1.4 on 2021-04-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_remove_song_song_uploadtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Song_Duration',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='song',
            name='Song_Name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='Song_Uploadtime',
            field=models.DateTimeField(default=None),
        ),
    ]
