# Generated by Django 3.1.4 on 2021-04-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_auto_20210416_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Title', models.CharField(max_length=100)),
                ('Book_Author', models.CharField(max_length=100)),
                ('Book_Narrator', models.CharField(max_length=100)),
                ('Book_Duration', models.PositiveIntegerField(default=None)),
                ('Book_Uploaddate', models.DateField(default=None)),
                ('Book_Uploadtime', models.TimeField(default=None)),
            ],
        ),
    ]
