# Generated by Django 3.1.4 on 2021-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_audiobook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Podcast_Name', models.CharField(max_length=100)),
                ('Podcast_Duration', models.PositiveIntegerField(default=None)),
                ('Podcast_Uploaddate', models.DateField(default=None)),
                ('Podcast_Uploadtime', models.TimeField(default=None)),
                ('Podcast_Host', models.CharField(max_length=100)),
                ('Podcast_Participants', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
