# Generated by Django 3.1.4 on 2021-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='Podcast_Participants_Count',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
    ]
